# Generated by Django 6.0.2 on 2026-03-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tempimage_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempimage',
            name='created_at',
        ),
    ]
